package com.acme.coldtrace.platform.reports.interfaces.rest;

import com.acme.coldtrace.platform.reports.application.commandservices.ReportAiSummaryCommandService;
import com.acme.coldtrace.platform.reports.application.commandservices.ReportCommandService;
import com.acme.coldtrace.platform.reports.domain.model.commands.GenerateReportAiSummaryCommand;
import com.acme.coldtrace.platform.reports.application.queryservices.ReportQueryService;
import com.acme.coldtrace.platform.reports.domain.model.queries.GetReportByIdAndOrganizationIdQuery;
import com.acme.coldtrace.platform.reports.domain.model.queries.GetReportsByOrganizationIdQuery;
import com.acme.coldtrace.platform.reports.interfaces.rest.resources.GenerateReportResource;
import com.acme.coldtrace.platform.reports.interfaces.rest.resources.ReportAiSummaryResource;
import com.acme.coldtrace.platform.reports.interfaces.rest.resources.ReportResource;
import com.acme.coldtrace.platform.reports.interfaces.rest.transform.GenerateReportCommandFromResourceAssembler;
import com.acme.coldtrace.platform.reports.interfaces.rest.transform.ResponseEntityFromReportAiSummaryCommandResultAssembler;
import com.acme.coldtrace.platform.reports.interfaces.rest.transform.ResponseEntityFromReportCommandResultAssembler;
import com.acme.coldtrace.platform.reports.interfaces.rest.transform.ResponseEntityFromReportQueryResultAssembler;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.MessageSource;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

/**
 * REST controller exposing report endpoints.
 * <p>
 * Reports are generated by the backend from persisted readings, incidents and
 * asset data. The controller only translates HTTP requests into command/query
 * objects and delegates metric computation to application services.
 *
 * @since 1.0
 */
@Slf4j
@RestController
@RequestMapping(value = "/organizations/{organizationId}/reports", produces = APPLICATION_JSON_VALUE)
@Tag(name = "Reports", description = "Endpoints for generated operational reports")
public class ReportsController {
    private final ReportAiSummaryCommandService reportAiSummaryCommandService;
    private final ReportCommandService reportCommandService;
    private final ReportQueryService reportQueryService;
    private final MessageSource messageSource;

    public ReportsController(
            ReportAiSummaryCommandService reportAiSummaryCommandService,
            ReportCommandService reportCommandService,
            ReportQueryService reportQueryService,
            MessageSource messageSource
    ) {
        this.reportAiSummaryCommandService = reportAiSummaryCommandService;
        this.reportCommandService = reportCommandService;
        this.reportQueryService = reportQueryService;
        this.messageSource = messageSource;
    }

    /**
     * Gets generated reports for an organization.
     *
     * @param organizationId organization identifier
     * @return response entity containing report resources
     */
    @Operation(summary = "Get reports by organization",
            description = "Gets generated operational reports owned by the provided organization")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Reports found",
                    content = @Content(array = @ArraySchema(schema = @Schema(implementation = ReportResource.class)))),
            @ApiResponse(responseCode = "400", description = "Missing or invalid organization identifier",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "404", description = "Organization not found",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
    })
    @GetMapping
    public ResponseEntity<?> getReportsByOrganizationId(
            @Parameter(name = "organizationId", description = "Organization identifier", required = true)
            @PathVariable Long organizationId) {
        log.debug("GET /organizations/{}/reports", organizationId);
        var result = reportQueryService.handle(new GetReportsByOrganizationIdQuery(organizationId));
        return ResponseEntityFromReportQueryResultAssembler.toResponseEntityFromListResult(result, messageSource);
    }

    /**
     * Gets one report by id.
     *
     * @param organizationId organization identifier
     * @param reportId report identifier
     * @return response entity containing one report resource
     */
    @Operation(summary = "Get report by id",
            description = "Gets one generated report owned by the provided organization")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Report found",
                    content = @Content(schema = @Schema(implementation = ReportResource.class))),
            @ApiResponse(responseCode = "400", description = "Missing or invalid identifier",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "404", description = "Organization or report not found",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
    })
    @GetMapping("/{reportId}")
    public ResponseEntity<?> getReportById(
            @Parameter(name = "organizationId", description = "Organization identifier", required = true)
            @PathVariable Long organizationId,
            @Parameter(name = "reportId", description = "Report identifier", required = true)
            @PathVariable Long reportId) {
        log.debug("GET /organizations/{}/reports/{}", organizationId, reportId);
        var result = reportQueryService.handle(new GetReportByIdAndOrganizationIdQuery(organizationId, reportId));
        return ResponseEntityFromReportQueryResultAssembler.toResponseEntityFromReportResult(result, messageSource);
    }

    /**
     * Generates an advisory AI summary for one existing report.
     *
     * @param organizationId organization identifier
     * @param reportId report identifier
     * @return response entity containing the generated advisory summary
     */
    @Operation(summary = "Generate a report AI summary",
            description = "Loads persisted report metrics and related evidence, then returns a structured advisory AI summary without mutating the source report")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "AI report summary generated",
                    content = @Content(schema = @Schema(implementation = ReportAiSummaryResource.class))),
            @ApiResponse(responseCode = "400", description = "Missing or invalid identifier",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "404", description = "Organization or report not found",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "500", description = "Report context could not be prepared",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "502", description = "AI provider returned invalid structured output",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "503", description = "AI provider is unavailable or disabled",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "504", description = "AI provider timed out",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
    })
    @PostMapping("/{reportId}/ai-summary")
    public ResponseEntity<?> generateReportAiSummary(
            @Parameter(name = "organizationId", description = "Organization identifier", required = true)
            @PathVariable Long organizationId,
            @Parameter(name = "reportId", description = "Report identifier", required = true)
            @PathVariable Long reportId) {
        log.debug("POST /organizations/{}/reports/{}/ai-summary", organizationId, reportId);
        var summary = reportAiSummaryCommandService.handle(
                new GenerateReportAiSummaryCommand(organizationId, reportId)
        );
        return ResponseEntityFromReportAiSummaryCommandResultAssembler.toResponseEntityFromGenerationResult(
                summary,
                messageSource
        );
    }

    /**
     * Generates a report for an organization and date range.
     *
     * @param organizationId organization identifier
     * @param resource report generation request
     * @return response entity containing generated report
     */
    @Operation(
            summary = "Generate a report",
            description = "Generates an operational report from persisted readings and incidents",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    required = true,
                    description = "Report generation request",
                    content = @Content(schema = @Schema(implementation = GenerateReportResource.class))))
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Report generated",
                    content = @Content(schema = @Schema(implementation = ReportResource.class))),
            @ApiResponse(responseCode = "400", description = "Bad request or invalid date range",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class))),
            @ApiResponse(responseCode = "404", description = "Organization not found",
                    content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
    })
    @PostMapping
    public ResponseEntity<?> generateReport(
            @Parameter(name = "organizationId", description = "Organization identifier", required = true)
            @PathVariable Long organizationId,
            @Valid @RequestBody GenerateReportResource resource) {
        log.debug("POST /organizations/{}/reports - type={}", organizationId, resource.type());
        var command = GenerateReportCommandFromResourceAssembler.toCommandFromResource(resource, organizationId);
        var result = reportCommandService.handle(command);
        return ResponseEntityFromReportCommandResultAssembler.toResponseEntityFromGenerationResult(
                result,
                messageSource
        );
    }
}
