package com.acme.coldtrace.platform.reports.domain.model.aggregates;

import com.acme.coldtrace.platform.reports.domain.model.events.ReportGeneratedEvent;
import com.acme.coldtrace.platform.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import lombok.Getter;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Report aggregate for the reports bounded context.
 * <p>
 * A report is a persisted operational snapshot generated by the backend from
 * readings, incidents and assets owned by an organization. It stores summary
 * metrics rather than raw embedded collections so the result remains stable,
 * compact and suitable for later export workflows.
 *
 * @since 1.0
 */
@Getter
public class Report extends AbstractDomainAggregateRoot<Report> {
    private Long id;
    private Long organizationId;
    private String uuid;
    private String type;
    private String title;
    private OffsetDateTime periodStart;
    private OffsetDateTime periodEnd;
    private OffsetDateTime generatedAt;
    private Integer assetCount;
    private Integer readingCount;
    private Integer outOfRangeReadingCount;
    private Integer incidentCount;
    private Integer openIncidentCount;
    private Double averageTemperature;
    private Double averageHumidity;
    private Double compliancePercentage;

    protected Report() {
    }

    /**
     * Creates a generated report aggregate.
     *
     * @param organizationId organization that owns the report
     * @param type report type
     * @param title human-readable title
     * @param periodStart inclusive lower data bound
     * @param periodEnd inclusive upper data bound
     * @param assetCount number of assets considered
     * @param readingCount number of readings considered
     * @param outOfRangeReadingCount number of out-of-range readings
     * @param incidentCount number of incidents considered
     * @param openIncidentCount number of unresolved incidents considered
     * @param averageTemperature average temperature across readings
     * @param averageHumidity average humidity across readings
     * @param compliancePercentage percentage of in-range readings
     */
    public Report(
            Long organizationId,
            String type,
            String title,
            OffsetDateTime periodStart,
            OffsetDateTime periodEnd,
            Integer assetCount,
            Integer readingCount,
            Integer outOfRangeReadingCount,
            Integer incidentCount,
            Integer openIncidentCount,
            Double averageTemperature,
            Double averageHumidity,
            Double compliancePercentage
    ) {
        this.organizationId = organizationId;
        this.uuid = "RPT-" + UUID.randomUUID();
        this.type = type;
        this.title = title;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
        this.generatedAt = OffsetDateTime.now();
        this.assetCount = assetCount;
        this.readingCount = readingCount;
        this.outOfRangeReadingCount = outOfRangeReadingCount;
        this.incidentCount = incidentCount;
        this.openIncidentCount = openIncidentCount;
        this.averageTemperature = averageTemperature;
        this.averageHumidity = averageHumidity;
        this.compliancePercentage = compliancePercentage;
    }

    /**
     * Rebuilds a report aggregate from persisted state.
     *
     * @param id persistence identifier
     * @param organizationId organization that owns the report
     * @param uuid external report identifier
     * @param type report type
     * @param title human-readable title
     * @param periodStart inclusive lower data bound
     * @param periodEnd inclusive upper data bound
     * @param generatedAt report generation timestamp
     * @param assetCount number of assets considered
     * @param readingCount number of readings considered
     * @param outOfRangeReadingCount number of out-of-range readings
     * @param incidentCount number of incidents considered
     * @param openIncidentCount number of unresolved incidents considered
     * @param averageTemperature average temperature across readings
     * @param averageHumidity average humidity across readings
     * @param compliancePercentage percentage of in-range readings
     */
    public Report(
            Long id,
            Long organizationId,
            String uuid,
            String type,
            String title,
            OffsetDateTime periodStart,
            OffsetDateTime periodEnd,
            OffsetDateTime generatedAt,
            Integer assetCount,
            Integer readingCount,
            Integer outOfRangeReadingCount,
            Integer incidentCount,
            Integer openIncidentCount,
            Double averageTemperature,
            Double averageHumidity,
            Double compliancePercentage
    ) {
        this.id = id;
        this.organizationId = organizationId;
        this.uuid = uuid;
        this.type = type;
        this.title = title;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
        this.generatedAt = generatedAt;
        this.assetCount = assetCount;
        this.readingCount = readingCount;
        this.outOfRangeReadingCount = outOfRangeReadingCount;
        this.incidentCount = incidentCount;
        this.openIncidentCount = openIncidentCount;
        this.averageTemperature = averageTemperature;
        this.averageHumidity = averageHumidity;
        this.compliancePercentage = compliancePercentage;
    }

    /**
     * Registers the domain event emitted after a report is generated.
     */
    public void onGenerated() {
        registerDomainEvent(ReportGeneratedEvent.from(this));
    }
}
