package com.acme.coldtrace.platform.assetmanagement.interfaces.rest.resources;

import java.time.LocalDate;
import java.util.List;

/**
 * Request resource used to create an IoT device.
 *
 * @param gatewayId connected gateway identifier
 * @param uuid device unique identifier
 * @param deviceType supported device type
 * @param model device model
 * @param measurementType human-readable measurement type
 * @param measurementParameters telemetry parameters generated by the device
 * @param readingFrequencySeconds expected reading cadence in seconds
 * @param assetId optional assigned asset identifier
 * @param status operational status
 * @param calibrationStatus calibration status
 * @param lastCalibrationDate last calibration date
 * @param nextCalibrationDate next calibration date
 * @since 1.0
 */
public record CreateIoTDeviceResource(
        Long gatewayId,
        String uuid,
        String deviceType,
        String model,
        String measurementType,
        List<String> measurementParameters,
        Integer readingFrequencySeconds,
        Long assetId,
        String status,
        String calibrationStatus,
        LocalDate lastCalibrationDate,
        LocalDate nextCalibrationDate
) {
}
