package com.acme.coldtrace.platform.aiassistance.application.model;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Advisory escalation decision generated by AI.
 *
 * @param recommended whether escalation is recommended
 * @param urgency suggested urgency level
 * @param reason reason for the escalation recommendation
 * @since 1.0
 */
@JsonPropertyOrder({"recommended", "urgency", "reason"})
public record EscalationRecommendationDraft(
        @NotNull Boolean recommended,
        @NotBlank @Size(max = 80) String urgency,
        @NotBlank @Size(max = 320) String reason
) {
}
